### ISSUE TITLE
タイトル解決済み表示する

### ISSUE THREAD

**Issue by catherine87** [vektor-inc/lightning-child-forum#1]
管理画面で投稿タイプ「トピック」の各記事編集画面にカスタムフィールドで『解決済み』のチェックボックスを追加する。
プラグインで設定しても良いし子テーマのfunctions.phpなどに手書きで書いても可。

チェックが入っているトピックスのタイトルは タイトルの前に [ 解決済 ] の文言が入るようにする。

タイトルを書き換えるフィルターは the_title なので

add_filter('the_title','vk_forum_title_custom');
function vk_forum_title_custom( $title ){
// カスタムフィールドの値を取得

// チェックが入っていたら
if (  ){
// タイトルの先頭に [ 解決済 ] を追加

}
// 値を返す

}

**Comment by kurudrive** [comment]
グッジョブです（・ｗ・
